apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-chart.fullname" . }}-config
  labels:
    {{- include "backend-chart.labels" . | nindent 4 }}
data:
  app.properties: |
    # Application Configuration
    server.port=8080
    logging.level.com.company.api=DEBUG

    # Database Configuration
    spring.datasource.url={{ .Values.env.DATABASE_URL }}

  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>
        <root level="INFO">
            <appender-ref ref="STDOUT" />
        </root>
    </configuration>
