apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app-a
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/6510685016/gitops-repo.git
    targetRevision: HEAD
    path: helm-charts/frontend-chart
    helm:
      valueFiles:
        - ../../apps/frontend/a/values.prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
