# Environment: SIT
# Application: frontend-app-a

replicaCount: 1

image:
  tag: "latest"

ingress:
  enabled: True
  host: frontend-app-a.sit.company.com
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
