# Default values for frontend-chart
replicaCount: 2

image:
  repository: nexus:8082/frontend-app
  pullPolicy: IfNotPresent
  tag: ""  # Overridden by environment values

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: "" # Overridden by env values
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
