# Environment: PROD
# Application: backend-api-b

replicaCount: 3

image:
  tag: "v1.2.3"

ingress:
  enabled: True
  host: backend-api-b.company.com
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
