# Environment: DEV
# Application: backend-api-b

replicaCount: 1

image:
  tag: "latest"

ingress:
  enabled: True
  host: backend-api-b.dev.company.com
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
