# Environment: UAT
# Application: frontend-app-b

replicaCount: 2

image:
  tag: "v1.2.3-rc1"

ingress:
  enabled: True
  host: frontend-app-b.uat.company.com
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi
